In [1]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import random

Problem 1: 

In [2]:
            #generating the array and and extracting antidiagonal elements

array = np.random.randint(1, 51, size=(5, 4))
print("Array:\n", array)

# Extracting antidiagonal elements
rows, columns = array.shape 
antidiagonals = []

for i in range(rows + columns - 1):
    diag = []
    for j in range(rows):
        k = i - j
       
        
        if (0 <= k < columns):
         diag.append(array[j][k])
    
    antidiagonals.append(diag)

# Printing the antidiagonals
for index, d in enumerate(antidiagonals):
    print(f"Antidiagonal {index}: {d}")

Array:
 [[ 2 21 15  8]
 [45 10  1 44]
 [21 22 29 33]
 [48  9 30  5]
 [42 39 36 32]]
Antidiagonal 0: [2]
Antidiagonal 1: [21, 45]
Antidiagonal 2: [15, 10, 21]
Antidiagonal 3: [8, 1, 22, 48]
Antidiagonal 4: [44, 29, 9, 42]
Antidiagonal 5: [33, 30, 39]
Antidiagonal 6: [5, 36]
Antidiagonal 7: [32]


In [3]:
        #computing and printing of maximum value of each row

for i in range(rows):
    mean = np.mean(array[i])
    print("Mean of row ",i ,"is", mean )
    

Mean of row  0 is 11.5
Mean of row  1 is 25.0
Mean of row  2 is 26.25
Mean of row  3 is 23.0
Mean of row  4 is 37.25


In [4]:
            # getting a array where elements are < or equal to over all mean
            #getting overall mean
            #initialising array 
Overall_mean=np.mean(array);
print("Overall_mean: ",Overall_mean)
Lesser_than_average=[]

for i in range(rows):
    for j in range (columns):
        if array[i][j]< Overall_mean:
         Lesser_than_average.append(array[i][j])

print("Array with valur less than overall mean: ",Lesser_than_average)


Overall_mean:  24.6
Array with valur less than overall mean:  [2, 21, 15, 8, 10, 1, 21, 22, 9, 5]


In [5]:
                # making of function 

In [6]:
def numpy_boundary_traversal(matrix):
    if matrix.ndim != 2:
        raise ValueError("Input must be a 2D NumPy array.")

    rows, cols = matrix.shape

    # If the matrix has only one row
    if rows == 1:
        return matrix[0].tolist()

    # If the matrix has only one column
    if cols == 1:
        return matrix[:, 0].tolist()

    boundary = []

    # Top row (left to right)
    for j in range(cols):
        boundary.append(matrix[0][j])

    # Right column (top to bottom, excluding first row)
    for i in range(1, rows):
        boundary.append(matrix[i][cols - 1])

    # Bottom row (right to left, excluding last column)
    if rows > 1: 
        for j in range(cols - 2, -1, -1):
            boundary.append(matrix[rows - 1][j])

    # Left column (bottom to top, excluding first and last rows)
    if cols > 1:
        for i in range(rows - 2, 0, -1):
            boundary.append(matrix[i][0])

    return boundary
        

In [7]:
numpy_boundary_traversal(array)

[2, 21, 15, 8, 44, 33, 5, 32, 36, 39, 42, 48, 21, 45]

Problem 2:

In [8]:
array_2 = np.random.uniform(1, 10, size=20)
print("Array:\n", array_2)

print("Minimum:", np.min(array_2))
print("Maximum:", np.max(array_2))
print("Median :", np.median(array_2))




Array:
 [3.2121829  6.90183426 6.85789781 6.86067673 5.10712677 3.29611629
 5.09212649 5.76467569 4.64137861 3.994587   3.04858849 1.23761077
 8.86728314 8.30028914 8.28358448 5.94742315 8.99435727 2.22312125
 6.70073862 4.93553517]
Minimum: 1.2376107688634557
Maximum: 8.994357271857597
Median : 5.435901228545825


In [9]:
modified_array_2 = np.copy(array_2)
modified_array_2[modified_array_2 < 5] = modified_array_2[modified_array_2 < 5] ** 2
print("Modified Array (elements < 5 squared):\n", modified_array_2)


Modified Array (elements < 5 squared):
 [10.31811901  6.90183426  6.85789781  6.86067673  5.10712677 10.86438259
  5.09212649  5.76467569 21.54239542 15.95672528  9.2938918   1.53168042
  8.86728314  8.30028914  8.28358448  5.94742315  8.99435727  4.94226807
  6.70073862 24.35950743]


In [10]:
def numpy_alternate_sort(array):
    sorted_array = np.sort(array)
    result = []

    left = 0
    right = len(sorted_array) - 1

    while left <= right:
        result.append(sorted_array[left])
        left += 1
        if left <= right:
            result.append(sorted_array[right])
            right -= 1

    return np.array(result)

numpy_alternate_sort(array_2)

array([1.23761077, 8.99435727, 2.22312125, 8.86728314, 3.04858849,
       8.30028914, 3.2121829 , 8.28358448, 3.29611629, 6.90183426,
       3.994587  , 6.86067673, 4.64137861, 6.85789781, 4.93553517,
       6.70073862, 5.09212649, 5.94742315, 5.10712677, 5.76467569])

Problem 3:

In [11]:
                #creating sampul data
names = ['Ayush', 'Bhaskar', 'Chaturvedi', 'Diwesh', 'Rkomm', 'Dinbandhu', 'Rahul', 'Lalmohan', 'Modi', 'Amit_Shah']
subjects = ['Math', 'Science', 'History', 'Civics', 'Geography', 'Politics', 'CS', 'PT', 'English', 'Sanskrit']

scores = np.random.randint(50, 101, size=10)
data = [(student, subject) for student in names for subject in subjects]

# Generate random scores between 50 and 100
scores = np.random.randint(50, 101, size=len(data))

# Create DataFrame
data_frame = pd.DataFrame(data, columns=['Name', 'Subject'])
data_frame['Score'] = scores

print("Original DataFrame:\n", data_frame)


Original DataFrame:
          Name    Subject  Score
0       Ayush       Math     91
1       Ayush    Science     67
2       Ayush    History     82
3       Ayush     Civics     70
4       Ayush  Geography     81
..        ...        ...    ...
95  Amit_Shah   Politics     58
96  Amit_Shah         CS     58
97  Amit_Shah         PT     89
98  Amit_Shah    English     75
99  Amit_Shah   Sanskrit     74

[100 rows x 3 columns]


In [12]:
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

data_frame['Grade'] = data_frame['Score'].apply(assign_grade)
print("Original DataFrame:\n", data_frame)

Original DataFrame:
          Name    Subject  Score Grade
0       Ayush       Math     91     A
1       Ayush    Science     67     D
2       Ayush    History     82     B
3       Ayush     Civics     70     C
4       Ayush  Geography     81     B
..        ...        ...    ...   ...
95  Amit_Shah   Politics     58     F
96  Amit_Shah         CS     58     F
97  Amit_Shah         PT     89     B
98  Amit_Shah    English     75     C
99  Amit_Shah   Sanskrit     74     C

[100 rows x 4 columns]


In [13]:
print("\nDataFrame Sorted by Score (Descending):")
print(data_frame.sort_values(by='Score', ascending=False))


DataFrame Sorted by Score (Descending):
          Name    Subject  Score Grade
44       Rkomm  Geography     99     A
70    Lalmohan       Math     98     A
11     Bhaskar    Science     98     A
78    Lalmohan    English     98     A
7        Ayush         PT     96     A
..         ...        ...    ...   ...
48       Rkomm    English     54     F
94   Amit_Shah  Geography     53     F
21  Chaturvedi    Science     52     F
81        Modi    Science     51     F
72    Lalmohan    History     51     F

[100 rows x 4 columns]


In [14]:
                #printing average of each subject
print("\nAverage Score Per Subject:")
print(data_frame.groupby('Subject')['Score'].mean())



Average Score Per Subject:
Subject
CS           70.7
Civics       84.9
English      77.3
Geography    74.5
History      70.3
Math         75.3
PT           80.8
Politics     72.9
Sanskrit     78.3
Science      68.6
Name: Score, dtype: float64


In [15]:
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

passed_df = pandas_filter_pass(data_frame)
print("\nStudents who scored A or B:\n", passed_df.head(100))  

print(passed_df.size/4)



Students who scored A or B:
           Name    Subject  Score Grade
0        Ayush       Math     91     A
2        Ayush    History     82     B
4        Ayush  Geography     81     B
5        Ayush   Politics     91     A
7        Ayush         PT     96     A
8        Ayush    English     93     A
11     Bhaskar    Science     98     A
13     Bhaskar     Civics     84     B
14     Bhaskar  Geography     88     B
19     Bhaskar   Sanskrit     90     A
22  Chaturvedi    History     91     A
23  Chaturvedi     Civics     80     B
29  Chaturvedi   Sanskrit     87     B
32      Diwesh    History     89     B
33      Diwesh     Civics     95     A
35      Diwesh   Politics     92     A
37      Diwesh         PT     89     B
44       Rkomm  Geography     99     A
46       Rkomm         CS     85     B
50   Dinbandhu       Math     87     B
53   Dinbandhu     Civics     90     A
56   Dinbandhu         CS     89     B
57   Dinbandhu         PT     86     B
58   Dinbandhu    English     90  